spring: 
  profiles: 
    active: 
      - dev

---
spring: 
  profiles: dev #开发环境
  application： 
    name: cloud-config-jsx-dev

---
spring: 
  profiles: test #测试环境
  application： 
    name: cloud-config-jsx-test

#注意  文件编码一定为utf-8